//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameStore.BLL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnumRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameStore.BLL.Resources.EnumRes", typeof(EnumRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пятьдесят.
        /// </summary>
        public static string Fifty {
            get {
                return ResourceManager.GetString("Fifty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Час.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Месяц.
        /// </summary>
        public static string month {
            get {
                return ResourceManager.GetString("month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Самые комментируемые.
        /// </summary>
        public static string MostCommented {
            get {
                return ResourceManager.GetString("MostCommented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Самые популярные.
        /// </summary>
        public static string MostPopular {
            get {
                return ResourceManager.GetString("MostPopular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По новизне.
        /// </summary>
        public static string NewByDate {
            get {
                return ResourceManager.GetString("NewByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сто.
        /// </summary>
        public static string OneHundred {
            get {
                return ResourceManager.GetString("OneHundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Год.
        /// </summary>
        public static string oneYear {
            get {
                return ResourceManager.GetString("oneYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По возрастанию стоимости.
        /// </summary>
        public static string PriceAsc {
            get {
                return ResourceManager.GetString("PriceAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По убыванию стоимости.
        /// </summary>
        public static string PriceDesc {
            get {
                return ResourceManager.GetString("PriceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Десять.
        /// </summary>
        public static string Ten {
            get {
                return ResourceManager.GetString("Ten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Три года.
        /// </summary>
        public static string threeYear {
            get {
                return ResourceManager.GetString("threeYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Двадцать.
        /// </summary>
        public static string Twenty {
            get {
                return ResourceManager.GetString("Twenty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Два года.
        /// </summary>
        public static string twoYear {
            get {
                return ResourceManager.GetString("twoYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неделя.
        /// </summary>
        public static string week {
            get {
                return ResourceManager.GetString("week", resourceCulture);
            }
        }
    }
}
