//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameStore.Web.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameStore.Web.App_LocalResources.GlobalRes", typeof(GlobalRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить игру к заказу.
        /// </summary>
        public static string AddGameToOrder {
            get {
                return ResourceManager.GetString("AddGameToOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to добавлена успешно.
        /// </summary>
        public static string addSucces {
            get {
                return ResourceManager.GetString("addSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ответить.
        /// </summary>
        public static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад к играм.
        /// </summary>
        public static string BackToGames {
            get {
                return ResourceManager.GetString("BackToGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забанить.
        /// </summary>
        public static string Ban {
            get {
                return ResourceManager.GetString("Ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Корзина.
        /// </summary>
        public static string Basket {
            get {
                return ResourceManager.GetString("Basket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Корзина пуста.
        /// </summary>
        public static string basketIsEmpty {
            get {
                return ResourceManager.GetString("basketIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщение.
        /// </summary>
        public static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Купить.
        /// </summary>
        public static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя владельца карты.
        /// </summary>
        public static string CardHoldersName {
            get {
                return ResourceManager.GetString("CardHoldersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя держателя карты может состоять только из символов, не менее 3.
        /// </summary>
        public static string CardHoldersNameExpression {
            get {
                return ResourceManager.GetString("CardHoldersNameExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер карты.
        /// </summary>
        public static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер карты может состоять только из цифр, не менее 3.
        /// </summary>
        public static string CardNumberExpression {
            get {
                return ResourceManager.GetString("CardNumberExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение верификации карты может состоять только из чисел, не менее 4, не более 6.
        /// </summary>
        public static string CardVerificationExpression {
            get {
                return ResourceManager.GetString("CardVerificationExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение Проверки Карты.
        /// </summary>
        public static string CardVerificationValue {
            get {
                return ResourceManager.GetString("CardVerificationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста
        /// выберите один или несколько жанров.
        /// </summary>
        public static string ChooseGenres {
            get {
                return ResourceManager.GetString("ChooseGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите роль как издателя, если вы хотите предоставить доступ для редактирования этого объекта.
        /// </summary>
        public static string ChoosePablisherRole {
            get {
                return ResourceManager.GetString("ChoosePablisherRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите картинку.
        /// </summary>
        public static string ChoosePicture {
            get {
                return ResourceManager.GetString("ChoosePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста
        ///выберите один или несколько типов платформ.
        /// </summary>
        public static string ChoosePlatformTypes {
            get {
                return ResourceManager.GetString("ChoosePlatformTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста
        /// выберите один или несколько ролей.
        /// </summary>
        public static string ChooseRoles {
            get {
                return ResourceManager.GetString("ChooseRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to заказ не может быть доставлен без оплаты его.
        /// </summary>
        public static string ChooseShippedDate {
            get {
                return ResourceManager.GetString("ChooseShippedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарии.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарии.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о компании.
        /// </summary>
        public static string CompanyInformation {
            get {
                return ResourceManager.GetString("CompanyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название компании.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите Пароль.
        /// </summary>
        public static string ConfirmePassword {
            get {
                return ResourceManager.GetString("ConfirmePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароли не совпадают.
        /// </summary>
        public static string ConfirmePasswordError {
            get {
                return ResourceManager.GetString("ConfirmePasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стоимость.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата от не может быть больше, чем дата до, выберите другую.
        /// </summary>
        public static string DataTimeFromTo {
            get {
                return ResourceManager.GetString("DataTimeFromTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата истечения срока действия.
        /// </summary>
        public static string DateOfExpity {
            get {
                return ResourceManager.GetString("DateOfExpity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to от.
        /// </summary>
        public static string DateTimeFrom {
            get {
                return ResourceManager.GetString("DateTimeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to до.
        /// </summary>
        public static string DateTimeTo {
            get {
                return ResourceManager.GetString("DateTimeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to День.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание Bank.
        /// </summary>
        public static string DescriptionBank {
            get {
                return ResourceManager.GetString("DescriptionBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание на английском языке.
        /// </summary>
        public static string DescriptionEn {
            get {
                return ResourceManager.GetString("DescriptionEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание IBox.
        /// </summary>
        public static string DescriptionIBox {
            get {
                return ResourceManager.GetString("DescriptionIBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание на русском языке.
        /// </summary>
        public static string DescriptionRu {
            get {
                return ResourceManager.GetString("DescriptionRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание Visa.
        /// </summary>
        public static string DescriptionVisa {
            get {
                return ResourceManager.GetString("DescriptionVisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детально.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скидка.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скидка.
        /// </summary>
        public static string Discountinues {
            get {
                return ResourceManager.GetString("Discountinues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скачать.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата окончания бана.
        /// </summary>
        public static string EndDateBaned {
            get {
                return ResourceManager.GetString("EndDateBaned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong login or password.
        /// </summary>
        public static string ErrorLogin {
            get {
                return ResourceManager.GetString("ErrorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение поля не может быть пустым.
        /// </summary>
        public static string Existent {
            get {
                return ResourceManager.GetString("Existent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жанр с таким именем уже существует, пожалуйста введите другое имя.
        /// </summary>
        public static string ExistGenreName {
            get {
                return ResourceManager.GetString("ExistGenreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такая связь не может существовать.
        /// </summary>
        public static string ExistGenreRelation {
            get {
                return ResourceManager.GetString("ExistGenreRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игра с таким ключом уже существует, пожалуйста введите другое имя.
        /// </summary>
        public static string ExistKey {
            get {
                return ResourceManager.GetString("ExistKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Платформа с таким именем уже существует, пожалуйста введите другое имя.
        /// </summary>
        public static string ExistPlatformTypeName {
            get {
                return ResourceManager.GetString("ExistPlatformTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Издатель с таким именем уже существует, введите другое имя.
        /// </summary>
        public static string ExistPublisherName {
            get {
                return ResourceManager.GetString("ExistPublisherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь с таким именем уже существует.
        /// </summary>
        public static string ExistUserName {
            get {
                return ResourceManager.GetString("ExistUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтровать.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтрация по периоду.
        /// </summary>
        public static string FilterDate {
            get {
                return ResourceManager.GetString("FilterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подписывайтесь на нас.
        /// </summary>
        public static string FollowUs {
            get {
                return ResourceManager.GetString("FollowUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Груз.
        /// </summary>
        public static string Freight {
            get {
                return ResourceManager.GetString("Freight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Из блога.
        /// </summary>
        public static string FromBlog {
            get {
                return ResourceManager.GetString("FromBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игра.
        /// </summary>
        public static string Game {
            get {
                return ResourceManager.GetString("Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игры.
        /// </summary>
        public static string Games {
            get {
                return ResourceManager.GetString("Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жанры.
        /// </summary>
        public static string Genres {
            get {
                return ResourceManager.GetString("Genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаленные игры.
        /// </summary>
        public static string GetAllDeleteGames {
            get {
                return ResourceManager.GetString("GetAllDeleteGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Связаться.
        /// </summary>
        public static string GetInTouch {
            get {
                return ResourceManager.GetString("GetInTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История заказов.
        /// </summary>
        public static string HistoryOrders {
            get {
                return ResourceManager.GetString("HistoryOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сайт издателя.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Час.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забанен.
        /// </summary>
        public static string IsBaned {
            get {
                return ResourceManager.GetString("IsBaned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплачено.
        /// </summary>
        public static string IsPaid {
            get {
                return ResourceManager.GetString("IsPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оставаться в системе.
        /// </summary>
        public static string IsPersistent {
            get {
                return ResourceManager.GetString("IsPersistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ключ.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ключ не может быть длиннее 200 символов и менее 3 символов и может содержать только A-Za-z0-9.
        /// </summary>
        public static string KeyRegexExpression {
            get {
                return ResourceManager.GetString("KeyRegexExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cсылки.
        /// </summary>
        public static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оформить заказ.
        /// </summary>
        public static string MakeOrder {
            get {
                return ResourceManager.GetString("MakeOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальная стоимость.
        /// </summary>
        public static string MaxPrice {
            get {
                return ResourceManager.GetString("MaxPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимальная цена должна быть меньше максимальной.
        /// </summary>
        public static string MinMaxPrice {
            get {
                return ResourceManager.GetString("MinMaxPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимальная Стоимость.
        /// </summary>
        public static string MinPrice {
            get {
                return ResourceManager.GetString("MinPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Месяц.
        /// </summary>
        public static string month {
            get {
                return ResourceManager.GetString("month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название на английском языке.
        /// </summary>
        public static string NameEn {
            get {
                return ResourceManager.GetString("NameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название не может быть длиннее 200 символов и менее 3 символов..
        /// </summary>
        public static string NameExpression3_200 {
            get {
                return ResourceManager.GetString("NameExpression3_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название не может быть длиннее 40 символов и менее 3 символов..
        /// </summary>
        public static string NameExpression3_40 {
            get {
                return ResourceManager.GetString("NameExpression3_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название на русском языке.
        /// </summary>
        public static string NameRu {
            get {
                return ResourceManager.GetString("NameRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не хватает игр на складе.
        /// </summary>
        public static string NotEnoughtGame {
            get {
                return ResourceManager.GetString("NotEnoughtGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас нет игр, созданных вами.
        /// </summary>
        public static string NothingToDisplay {
            get {
                return ResourceManager.GetString("NothingToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас нет объекта издателя.
        /// </summary>
        public static string NothingToEdit {
            get {
                return ResourceManager.GetString("NothingToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ничего не найдено.
        /// </summary>
        public static string NothingWasFound {
            get {
                return ResourceManager.GetString("NothingWasFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Год.
        /// </summary>
        public static string oneYear {
            get {
                return ResourceManager.GetString("oneYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id заказа.
        /// </summary>
        public static string OrderId {
            get {
                return ResourceManager.GetString("OrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказы.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество элементов на странице.
        /// </summary>
        public static string PageSize {
            get {
                return ResourceManager.GetString("PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название родительского жанра.
        /// </summary>
        public static string ParentGenreName {
            get {
                return ResourceManager.GetString("ParentGenreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль не может быть длиннее 40 символов и менее 3 символов..
        /// </summary>
        public static string PasswordExpression3_40 {
            get {
                return ResourceManager.GetString("PasswordExpression3_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплатить.
        /// </summary>
        public static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Навсегда.
        /// </summary>
        public static string Permanent {
            get {
                return ResourceManager.GetString("Permanent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Личный кабинет.
        /// </summary>
        public static string PersonalArea {
            get {
                return ResourceManager.GetString("PersonalArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Картинка.
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Типы платформ.
        /// </summary>
        public static string PlatformTypes {
            get {
                return ResourceManager.GetString("PlatformTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Год.
        /// </summary>
        public static string pneYear {
            get {
                return ResourceManager.GetString("pneYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стоимость.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Издатель.
        /// </summary>
        public static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Издатели.
        /// </summary>
        public static string Publishers {
            get {
                return ResourceManager.GetString("Publishers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цитировать.
        /// </summary>
        public static string Quote {
            get {
                return ResourceManager.GetString("Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрироваться.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возобновить.
        /// </summary>
        public static string Renew {
            get {
                return ResourceManager.GetString("Renew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роли.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск игры по названию.
        /// </summary>
        public static string SearchGameName {
            get {
                return ResourceManager.GetString("SearchGameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес Доставки.
        /// </summary>
        public static string ShipAddress {
            get {
                return ResourceManager.GetString("ShipAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Город доставки.
        /// </summary>
        public static string ShipCity {
            get {
                return ResourceManager.GetString("ShipCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страна доставки.
        /// </summary>
        public static string ShipCountry {
            get {
                return ResourceManager.GetString("ShipCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название поставщика.
        /// </summary>
        public static string ShipName {
            get {
                return ResourceManager.GetString("ShipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата доставки.
        /// </summary>
        public static string ShippedDate {
            get {
                return ResourceManager.GetString("ShippedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поставщик.
        /// </summary>
        public static string Shipper {
            get {
                return ResourceManager.GetString("Shipper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почтовый Индекс.
        /// </summary>
        public static string ShipPostalCode {
            get {
                return ResourceManager.GetString("ShipPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регион.
        /// </summary>
        public static string ShipRegion {
            get {
                return ResourceManager.GetString("ShipRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доставить через.
        /// </summary>
        public static string ShipViaName {
            get {
                return ResourceManager.GetString("ShipViaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип сортировки.
        /// </summary>
        public static string SortType {
            get {
                return ResourceManager.GetString("SortType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата начала бана.
        /// </summary>
        public static string StartDateBaned {
            get {
                return ResourceManager.GetString("StartDateBaned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать заказы за период.
        /// </summary>
        public static string TakeOrderBetween {
            get {
                return ResourceManager.GetString("TakeOrderBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Три года.
        /// </summary>
        public static string threeYear {
            get {
                return ResourceManager.GetString("threeYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Двадцать.
        /// </summary>
        public static string Twenty {
            get {
                return ResourceManager.GetString("Twenty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Два года.
        /// </summary>
        public static string twoYear {
            get {
                return ResourceManager.GetString("twoYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В наличии.
        /// </summary>
        public static string UnitsInStock {
            get {
                return ResourceManager.GetString("UnitsInStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to обновления.
        /// </summary>
        public static string updates {
            get {
                return ResourceManager.GetString("updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id пользователя.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин не может быть длиннее 40 символов и менее 3 символов..
        /// </summary>
        public static string UserNameExpression3_40 {
            get {
                return ResourceManager.GetString("UserNameExpression3_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посетить блог.
        /// </summary>
        public static string VisitBlog {
            get {
                return ResourceManager.GetString("VisitBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неделя.
        /// </summary>
        public static string week {
            get {
                return ResourceManager.GetString("week", resourceCulture);
            }
        }
    }
}
