// <auto-generated />
namespace GameStore.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatecomment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatecomment));
        
        string IMigrationMetadata.Id
        {
            get { return "201804130915491_update comment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
