// <auto-generated />
namespace GameStore.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class upd2task4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(upd2task4));
        
        string IMigrationMetadata.Id
        {
            get { return "201805211545172_upd2 task4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
